### ISSUE TITLE
"OpenSSL SSL_read: error" from `get_table_data` where `get_gen` works fine

### ISSUE THREAD

**Issue by vcameron1** [ReseauBiodiversiteQuebec/ratlas#31]
Error produced when large amounts of data is queried.

```r
get_table_data("taxa_ref")
get_gen("taxa_ref")
```

**Comment by BenMerSci** [comment]
Error is caused by the curl package on Ubuntu (or Linux overall?)
No fix available for curl package < 7.87.0. which is available on Ubuntu version 23.04 and above.
(https://github.com/curl/curl/issues/9931)
